# Generated by Django 5.2.1 on 2026-03-13 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_escola_turma_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_destino', models.CharField(max_length=20)),
                ('hash_evento', models.CharField(max_length=64)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='enviado', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendaevento')),
            ],
        ),
    ]
