# Generated by Django 5.2.1 on 2026-03-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=False)),
            ],
        ),
    ]
